<?php
return [
    'BE' => [
        'debug' => false,
        'explicitADmode' => 'explicitAllow',
        'installToolPassword' => '$pbkdf2-sha256$25000$si4QJGm3g87AlSG6wYywpg$lSatu435unxosyDtioZ8RtT/osNYJmVV3799oGlCJ5E',
        'loginSecurityLevel' => 'rsa',
        'versionNumberInFilename' => true,
        'warning_email_addr' => 'viktor.livakivskyi@oddity.agency',
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8',
                'dbname' => 'typo3-main',
                'driver' => 'mysqli',
                'host' => 'typo3-mysql-main',
                'password' => 'xui622zAz7Gtgu5Y',
                'port' => 3306,
                'user' => 'typo3',
            ],
            'Index' => [
                'charset' => 'utf8',
                'dbname' => 'typo3-index',
                'driver' => 'mysqli',
                'host' => 'typo3-mysql-index',
                'password' => 'xui622zAz7Gtgu5Y',
                'port' => 3306,
                'user' => 'typo3',
            ],
            'Sys' => [
                'charset' => 'utf8',
                'dbname' => 'typo3-sys',
                'driver' => 'mysqli',
                'host' => 'typo3-mysql-sys',
                'password' => 'xui622zAz7Gtgu5Y',
                'port' => 3306,
                'user' => 'typo3',
            ],
        ],
        'TableMapping' => [
            'index_debug' => 'Index',
            'index_fulltext' => 'Index',
            'index_grlist' => 'Index',
            'index_phash' => 'Index',
            'index_rel' => 'Index',
            'index_section' => 'Index',
            'index_words' => 'Index',
            'sys_history' => 'Sys',
            'sys_log' => 'Sys',
        ],
    ],
    'EXT' => [
        'extConf' => [
            'indexed_search' => 'a:19:{s:8:"pdftools";s:9:"/usr/bin/";s:8:"pdf_mode";s:2:"20";s:5:"unzip";s:9:"/usr/bin/";s:6:"catdoc";s:9:"/usr/bin/";s:6:"xlhtml";s:9:"/usr/bin/";s:7:"ppthtml";s:9:"/usr/bin/";s:5:"unrtf";s:9:"/usr/bin/";s:9:"debugMode";s:1:"0";s:18:"fullTextDataLength";s:1:"0";s:23:"disableFrontendIndexing";s:1:"0";s:21:"enableMetaphoneSearch";s:1:"1";s:6:"minAge";s:2:"24";s:6:"maxAge";s:1:"0";s:16:"maxExternalFiles";s:1:"5";s:26:"useCrawlerForExternalFiles";s:1:"0";s:11:"flagBitMask";s:3:"192";s:16:"ignoreExtensions";s:0:"";s:17:"indexExternalURLs";s:1:"0";s:16:"useMysqlFulltext";s:1:"1";}',
            'my_redirects' => 'a:0:{}',
            'opendocs' => 'a:0:{}',
            'recycler' => 'a:0:{}',
            'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
            'rte_ckeditor' => 'a:0:{}',
            'saltedpasswords' => 'a:6:{s:20:"checkConfigurationFE";s:1:"0";s:20:"checkConfigurationBE";s:1:"0";s:3:"FE.";a:5:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\Pbkdf2Salt";s:11:"forceSalted";s:1:"1";s:15:"onlyAuthService";s:1:"0";s:12:"updatePasswd";s:1:"0";}s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\Pbkdf2Salt";s:11:"forceSalted";s:1:"0";s:15:"onlyAuthService";s:1:"1";s:12:"updatePasswd";s:1:"1";}s:21:"checkConfigurationFE2";s:1:"0";s:21:"checkConfigurationBE2";s:1:"0";}',
            'scheduler' => 'a:4:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";}',
            'typoscript_rendering' => 'a:0:{}',
            'vhs' => 'a:1:{s:20:"disableAssetHandling";s:1:"1";}',
        ],
    ],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [
                'de',
            ],
        ],
    ],
    'FE' => [
        'cHashExcludedParameters' => 'L, pk_campaign, pk_kwd, pk_vid, utm_source, utm_medium, utm_campaign, utm_term, utm_content',
        'debug' => false,
        'disableNoCacheParameter' => true,
        'loginSecurityLevel' => 'rsa',
        'noPHPscriptInclude' => true,
        'versionNumberInFilename' => 'embed',
    ],
    'GFX' => [
        'gdlib_png' => true,
        'jpg_quality' => 90,
        'processor' => 'GraphicsMagick',
        'processor_allowTemporaryMasksAsPng' => false,
        'processor_colorspace' => 'RGB',
        'processor_effects' => -1,
        'processor_enabled' => true,
        'processor_path' => '/usr/bin/',
        'processor_path_lzw' => '/usr/bin/',
    ],
    'MAIL' => [
        'transport_sendmail_command' => '/usr/sbin/sendmail -t -i ',
    ],
    'SYS' => [
        'UTF8filesystem' => true,
        'devIPmask' => '',
        'displayErrors' => 0,
        'enableDeprecationLog' => false,
        'encryptionKey' => '12d5b12ed61e8f3e020a94a4dbd40a185a773482fbe78a2d365317fee394f31adfde4799eceb4256838420870ca424b7',
        'exceptionalErrors' => 20480,
        'fileCreateMask' => '0644',
        'folderCreateMask' => '2755',
        'isInitialDatabaseImportDone' => true,
        'isInitialInstallationInProgress' => false,
        'mediafile_ext' => 'gif,jpg,jpeg,bmp,png,pdf,svg,ai,youtube',
        'phpTimeZone' => 'Europe/Berlin',
        'sitename' => 'Docker TYPO3',
        'sqlDebug' => 0,
        'systemLocale' => 'de_DE.utf8',
        'systemLog' => 'error_log',
        'systemLogLevel' => 2,
    ],
];
